### ISSUE TITLE
CDN process dies - wget library

### ISSUE THREAD

**Issue by fra967** [dadi/cdn#366]
CDN 2.0.0 occasionally crashing and restarting, and logging the error below

```
/dadi/cdn/node_modules/wget-improved/lib/wget.js:208
    return str.trim().toLowerCase().replace(/:$/, '');
               ^

TypeError: Cannot read property 'trim' of null
    at cleanProtocol (/dadi/cdn/node_modules/wget-improved/lib/wget.js:208:16)
    at download (/dadi/cdn/node_modules/wget-improved/lib/wget.js:37:23)
    at ClientRequest.<anonymous> (/dadi/cdn/node_modules/wget-improved/lib/wget.js:57:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

I am trying to identify the request that creates this error

**Comment by fra967** [comment]
byu the way, I had to add wget-improved as a dependency, otherwise CDN will not start

```
Error: Cannot find module 'wget-improved'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
```

**Comment by jimlambie** [comment]
@fra967 for now can you please try installing `@dadi/wget` to see if this resolves?

**Comment by fra967** [comment]
this error occurs with CDN 1.13.3 as well

It happens when accessing a remote URL, which then redirects to a relative path

this is bad practice, as 301s should always be fully qualified URLs, however we have to expect anything when hitting a remote server and deal with dodgy responses like this one

example IMG URL
```
Request URL:http://www.domain.com/image.jpg
Request Method:GET
Status Code:301 Moved Permanently
```

Response Headers
```
Location:/en/image.jpg
```

this will pass `/en/image.jpg` to the wget library which will then fail with the above error

**Comment by eduardoboucas** [comment]
CDN no longer uses wget, so I'm assuming this is not an issue anymore. Can we close this, or do we need to fix an earlier version of the product?

**Comment by fra967** [comment]
Yes we can close it, it was an edge case any way
